# Generated by Django 5.0.2 on 2024-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_images', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
