# Generated by Django 5.0.6 on 2024-07-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authon',
            new_name='author',
        ),
    ]
